source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.1.4'
gem 'sqlite3'
gem 'puma', '~> 3.7'
gem 'kaminari', '~> 1.1'
gem 'devise'
gem 'slim'
gem 'turbolinks'
gem 'simple_form'
gem 'rails-rapido', path: '../../../rapido'

group :development, :test do
  gem 'pry-byebug'
  gem 'capybara'
  gem 'cucumber', '2.4.0'
  gem 'cucumber-rails', require: false
  gem 'cucumber-api-steps', github: 'jayzes/cucumber-api-steps'
  gem 'cucumber-persona'
  gem 'cucumber_priority'
  gem 'database_cleaner'
  gem 'spreewald', github: 'makandra/spreewald'
  gem 'rspec-rails'
end
