source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


gem 'rails', '~> 5.1.4'
gem 'sqlite3'
gem 'puma', '~> 3.7'

group :development, :test do
  gem 'pry-byebug'
  gem 'cucumber', '~> 3.0'
  gem 'cucumber-rails', require: false
  gem 'cucumber-api-steps', github: 'jayzes/cucumber-api-steps'
  gem 'cucumber-persona'
  gem 'database_cleaner'
  gem 'rspec-rails'
end
